### ISSUE TITLE
Please update to the new version of 1.8 that has singleplayer

### ISSUE THREAD

**Issue by eagler69420** [eaglercraftx1-8/eaglercraftx1-8.github.io#2]
This "1.8.9" client is FAKE, it is a broken preview build of EaglercraftX 1.8 from 2022 with a few strings modifed.

Update to the latest version, EaglercraftX 1.8 u34 on git.eaglercraft.rip includes additional features like **singleplayer** and **shaders** and hundreds of bugfixes.

The latest can be downloaded from [https://git.eaglercraft.rip/eaglercraft/eaglercraft-builds/src/branch/main/EaglercraftX_1.8_Web.zip](https://git.eaglercraft.rip/eaglercraft/eaglercraft-builds/src/branch/main/EaglercraftX_1.8_Web.zip)

Last updated on June 8th 2024

Thanks.

**Comment by PrestonT500** [comment]
Done @eagler69420
