### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by sosaaaaaaaaaaaaaaaaa** [eaglercraftx1-8/eaglercraftx1-8.github.io#8]
could you add eaglercraft 1.7.3 and/or Infdev beta by Peytonplayz595? there is a html file with Peytonplayz595's Infdev on the internet archive, and the 1.7.3 github page is still up

**Comment by PrestonT500** [comment]
@sosaaaaaaaaaaaaaaaaa could you send a link?

**Comment by sosaaaaaaaaaaaaaaaaa** [comment]
1.7.3 beta: https://peytonplayz595.github.io/Beta-1.7.3/web/ github: https://github.com/PeytonPlayz595/Beta-1.7.3

Infdev Internet Archive: https://archive.org/details/infdev-20100630-1

**Comment by PrestonT500** [comment]
alright ill add it in a bit

**Comment by SOSgaming1** [comment]
sweet. ive been waiting for some new versions.

**Comment by PrestonT500** [comment]
@SOSgaming1 if you join the discord server we have a suggestions channel
